// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: panel

#include "../ui.h"

void ui_Main_Screen_screen_init(void)
{
    ui_Main_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slave_Dropdown = lv_dropdown_create(ui_Main_Screen);
    lv_dropdown_set_options(ui_Slave_Dropdown, "");
    lv_dropdown_set_text(ui_Slave_Dropdown, "Device:");
    lv_obj_set_width(ui_Slave_Dropdown, lv_pct(80));
    lv_obj_set_height(ui_Slave_Dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slave_Dropdown, 0);
    lv_obj_set_y(ui_Slave_Dropdown, lv_pct(10));
    lv_obj_set_align(ui_Slave_Dropdown, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Slave_Dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Info_Panel = lv_obj_create(ui_Main_Screen);
    lv_obj_set_width(ui_Info_Panel, lv_pct(80));
    lv_obj_set_height(ui_Info_Panel, lv_pct(40));
    lv_obj_set_x(ui_Info_Panel, 0);
    lv_obj_set_y(ui_Info_Panel, lv_pct(-9));
    lv_obj_set_align(ui_Info_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Info_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Control_Panel = lv_obj_create(ui_Main_Screen);
    lv_obj_set_width(ui_Control_Panel, lv_pct(80));
    lv_obj_set_height(ui_Control_Panel, lv_pct(30));
    lv_obj_set_x(ui_Control_Panel, 0);
    lv_obj_set_y(ui_Control_Panel, lv_pct(29));
    lv_obj_set_align(ui_Control_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Control_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TDS_Text = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_TDS_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TDS_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TDS_Text, lv_pct(20));
    lv_obj_set_y(ui_TDS_Text, lv_pct(-23));
    lv_obj_set_align(ui_TDS_Text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TDS_Text, "TDS Value:");

    ui_pH_Text = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_pH_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pH_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pH_Text, lv_pct(20));
    lv_obj_set_y(ui_pH_Text, lv_pct(-17));
    lv_obj_set_align(ui_pH_Text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_pH_Text, "pH   Value:");

    ui_NTU_Text = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_NTU_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NTU_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NTU_Text, lv_pct(20));
    lv_obj_set_y(ui_NTU_Text, lv_pct(-11));
    lv_obj_set_align(ui_NTU_Text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NTU_Text, "NTU Value:");

    ui_Water_Level_Text = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_Water_Level_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Water_Level_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Water_Level_Text, lv_pct(20));
    lv_obj_set_y(ui_Water_Level_Text, lv_pct(-5));
    lv_obj_set_align(ui_Water_Level_Text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Water_Level_Text, "Water Level:");

    ui_Water_Temperature = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_Water_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Water_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Water_Temperature, 1);
    lv_obj_set_x(ui_Water_Temperature, lv_pct(20));
    lv_obj_set_align(ui_Water_Temperature, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Water_Temperature, "Water Temperature:");

    ui_TDS_Value = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_TDS_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TDS_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TDS_Value, lv_pct(-15));
    lv_obj_set_y(ui_TDS_Value, lv_pct(-23));
    lv_obj_set_align(ui_TDS_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TDS_Value, "-");

    ui_pH_Value = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_pH_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pH_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pH_Value, lv_pct(-15));
    lv_obj_set_y(ui_pH_Value, lv_pct(-17));
    lv_obj_set_align(ui_pH_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_pH_Value, "-");

    ui_NTH_Value = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_NTH_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NTH_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NTH_Value, lv_pct(-15));
    lv_obj_set_y(ui_NTH_Value, lv_pct(-11));
    lv_obj_set_align(ui_NTH_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_NTH_Value, "-");

    ui_Water_Level_Value = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_Water_Level_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Water_Level_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Water_Level_Value, lv_pct(-15));
    lv_obj_set_y(ui_Water_Level_Value, lv_pct(-5));
    lv_obj_set_align(ui_Water_Level_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Water_Level_Value, "-");

    ui_Water_Temperature_Value = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_Water_Temperature_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Water_Temperature_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Water_Temperature_Value, lv_pct(-15));
    lv_obj_set_y(ui_Water_Temperature_Value, lv_pct(1));
    lv_obj_set_align(ui_Water_Temperature_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Water_Temperature_Value, "-");

    ui_Pump = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_Pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pump, lv_pct(20));
    lv_obj_set_y(ui_Pump, lv_pct(20));
    lv_obj_set_align(ui_Pump, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Pump, "Pump");

    ui_Camera_Text = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_Camera_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Camera_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Camera_Text, lv_pct(20));
    lv_obj_set_y(ui_Camera_Text, lv_pct(26));
    lv_obj_set_align(ui_Camera_Text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Camera_Text, "Camera");

    ui_Feed_Text = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_Feed_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Feed_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Feed_Text, lv_pct(20));
    lv_obj_set_y(ui_Feed_Text, lv_pct(32));
    lv_obj_set_align(ui_Feed_Text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Feed_Text, "Feed");

    ui_Pump_Switch = lv_switch_create(ui_Main_Screen);
    lv_obj_set_width(ui_Pump_Switch, 50);
    lv_obj_set_height(ui_Pump_Switch, 25);
    lv_obj_set_x(ui_Pump_Switch, lv_pct(-15));
    lv_obj_set_y(ui_Pump_Switch, lv_pct(20));
    lv_obj_set_align(ui_Pump_Switch, LV_ALIGN_RIGHT_MID);

    ui_Camera_Button = lv_btn_create(ui_Main_Screen);
    lv_obj_set_width(ui_Camera_Button, 50);
    lv_obj_set_height(ui_Camera_Button, 25);
    lv_obj_set_x(ui_Camera_Button, lv_pct(-15));
    lv_obj_set_y(ui_Camera_Button, lv_pct(26));
    lv_obj_set_align(ui_Camera_Button, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Camera_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Camera_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Feed_Button = lv_btn_create(ui_Main_Screen);
    lv_obj_set_width(ui_Feed_Button, 50);
    lv_obj_set_height(ui_Feed_Button, 25);
    lv_obj_set_x(ui_Feed_Button, lv_pct(-15));
    lv_obj_set_y(ui_Feed_Button, lv_pct(32));
    lv_obj_set_align(ui_Feed_Button, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Feed_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Feed_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TDS_Icon = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_TDS_Icon, &ui_img_tds_png);
    lv_obj_set_width(ui_TDS_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TDS_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TDS_Icon, lv_pct(14));
    lv_obj_set_y(ui_TDS_Icon, lv_pct(-23));
    lv_obj_set_align(ui_TDS_Icon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_TDS_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TDS_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pH_Icon = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_pH_Icon, &ui_img_ph_png);
    lv_obj_set_width(ui_pH_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pH_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pH_Icon, lv_pct(14));
    lv_obj_set_y(ui_pH_Icon, lv_pct(-17));
    lv_obj_set_align(ui_pH_Icon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_pH_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pH_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NTH_Icon = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_NTH_Icon, &ui_img_nth_png);
    lv_obj_set_width(ui_NTH_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NTH_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NTH_Icon, lv_pct(14));
    lv_obj_set_y(ui_NTH_Icon, lv_pct(-11));
    lv_obj_set_align(ui_NTH_Icon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_NTH_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NTH_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Water_Level_Icon = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_Water_Level_Icon, &ui_img_water_level_png);
    lv_obj_set_width(ui_Water_Level_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Water_Level_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Water_Level_Icon, lv_pct(14));
    lv_obj_set_y(ui_Water_Level_Icon, lv_pct(-5));
    lv_obj_set_align(ui_Water_Level_Icon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Water_Level_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Water_Level_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Water_Temperature_Icon = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_Water_Temperature_Icon, &ui_img_water_temperature_png);
    lv_obj_set_width(ui_Water_Temperature_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Water_Temperature_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Water_Temperature_Icon, lv_pct(14));
    lv_obj_set_y(ui_Water_Temperature_Icon, lv_pct(1));
    lv_obj_set_align(ui_Water_Temperature_Icon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Water_Temperature_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Water_Temperature_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pump_Icon = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_Pump_Icon, &ui_img_pump_png);
    lv_obj_set_width(ui_Pump_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pump_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pump_Icon, lv_pct(14));
    lv_obj_set_y(ui_Pump_Icon, lv_pct(20));
    lv_obj_set_align(ui_Pump_Icon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Pump_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pump_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Camera_Icon = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_Camera_Icon, &ui_img_camera_png);
    lv_obj_set_width(ui_Camera_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Camera_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Camera_Icon, lv_pct(14));
    lv_obj_set_y(ui_Camera_Icon, lv_pct(26));
    lv_obj_set_align(ui_Camera_Icon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Camera_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Camera_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Feed_Icon = lv_img_create(ui_Main_Screen);
    lv_img_set_src(ui_Feed_Icon, &ui_img_feeding_png);
    lv_obj_set_width(ui_Feed_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Feed_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Feed_Icon, lv_pct(14));
    lv_obj_set_y(ui_Feed_Icon, lv_pct(32));
    lv_obj_set_align(ui_Feed_Icon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Feed_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Feed_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifi_Button = lv_imgbtn_create(ui_Main_Screen);
    lv_imgbtn_set_src(ui_Wifi_Button, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi_png, NULL);
    lv_obj_set_width(ui_Wifi_Button, 24);
    lv_obj_set_height(ui_Wifi_Button, 24);
    lv_obj_set_x(ui_Wifi_Button, lv_pct(3));
    lv_obj_set_y(ui_Wifi_Button, lv_pct(3));
    lv_obj_add_flag(ui_Wifi_Button, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Feed_Dropdown = lv_dropdown_create(ui_Main_Screen);
    lv_dropdown_set_options(ui_Feed_Dropdown, "Disabled\n1 Hour\n6 Hours\n12 Hours");
    lv_obj_set_width(ui_Feed_Dropdown, 150);
    lv_obj_set_height(ui_Feed_Dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Feed_Dropdown, 0);
    lv_obj_set_y(ui_Feed_Dropdown, lv_pct(32));
    lv_obj_set_align(ui_Feed_Dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Feed_Dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  

    lv_obj_add_event_cb(ui_Slave_Dropdown, ui_event_Slave_Dropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pump_Switch, ui_event_Pump_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Camera_Button, ui_event_Camera_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Feed_Button, ui_event_Feed_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifi_Button, ui_event_Wifi_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Feed_Dropdown, ui_event_Feed_Dropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_Screen, ui_event_Main_Screen, LV_EVENT_ALL, NULL);

}
