// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: panel

#include "../ui.h"

void ui_QR_Code_screen_init(void)
{
    ui_QR_Code = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_QR_Code, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_QR_Code_Back_Button = lv_imgbtn_create(ui_QR_Code);
    lv_imgbtn_set_src(ui_QR_Code_Back_Button, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_906722072, NULL);
    lv_obj_set_width(ui_QR_Code_Back_Button, 50);
    lv_obj_set_height(ui_QR_Code_Back_Button, 50);
    lv_obj_set_x(ui_QR_Code_Back_Button, lv_pct(-5));
    lv_obj_set_y(ui_QR_Code_Back_Button, lv_pct(5));
    lv_obj_set_align(ui_QR_Code_Back_Button, LV_ALIGN_TOP_RIGHT);

    lv_color_t bg_color = lv_palette_lighten(LV_PALETTE_LIGHT_BLUE, 5);
    lv_color_t fg_color = lv_palette_darken(LV_PALETTE_BLUE, 4);
    ui_QR_Code_Image = lv_qrcode_create(ui_QR_Code, 320, fg_color, bg_color);
    lv_obj_set_x(ui_QR_Code_Image, 0);
    lv_obj_set_y(ui_QR_Code_Image, 0);
    lv_obj_set_align(ui_QR_Code_Image, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_QR_Code_Image, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    /*Set data*/
    const char * data = "https://github.com/EspressifApp/EsptouchForAndroid";
    lv_qrcode_update(ui_QR_Code_Image, data, strlen(data));
    lv_obj_center(ui_QR_Code_Image);

    /*Add a border with bg_color*/
    lv_obj_set_style_border_color(ui_QR_Code_Image, bg_color, 0);
    lv_obj_set_style_border_width(ui_QR_Code_Image, 5, 0);

    ui_UpdateDropdown = lv_dropdown_create(ui_QR_Code);
    lv_dropdown_set_options(ui_UpdateDropdown, "1 Minute\n5 Minute\n10 Minute");
    lv_obj_set_width(ui_UpdateDropdown, 320);
    lv_obj_set_height(ui_UpdateDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpdateDropdown, 0);
    lv_obj_set_y(ui_UpdateDropdown, 200);
    lv_obj_set_align(ui_UpdateDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpdateDropdown, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_QR_Code_Back_Button, ui_event_QR_Code_Back_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_QR_Code, ui_event_QR_Code, LV_EVENT_ALL, NULL);

}
