// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: panel

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_QR_Code
void ui_QR_Code_screen_init(void);
void ui_event_QR_Code(lv_event_t * e);
lv_obj_t * ui_QR_Code;
void ui_event_QR_Code_Back_Button(lv_event_t * e);
lv_obj_t * ui_QR_Code_Back_Button;
lv_obj_t * ui_QR_Code_Image;
lv_obj_t * ui_UpdateDropdown;

// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
void ui_event_Main_Screen(lv_event_t * e);
lv_obj_t * ui_Main_Screen;
void ui_event_Slave_Dropdown(lv_event_t * e);
lv_obj_t * ui_Slave_Dropdown;
lv_obj_t * ui_Info_Panel;
lv_obj_t * ui_Control_Panel;
lv_obj_t * ui_TDS_Text;
lv_obj_t * ui_pH_Text;
lv_obj_t * ui_NTU_Text;
lv_obj_t * ui_Water_Level_Text;
lv_obj_t * ui_Water_Temperature;
lv_obj_t * ui_TDS_Value;
lv_obj_t * ui_pH_Value;
lv_obj_t * ui_NTH_Value;
lv_obj_t * ui_Water_Level_Value;
lv_obj_t * ui_Water_Temperature_Value;
lv_obj_t * ui_Pump;
lv_obj_t * ui_Camera_Text;
lv_obj_t * ui_Feed_Text;
void ui_event_Pump_Switch(lv_event_t * e);
lv_obj_t * ui_Pump_Switch;
void ui_event_Camera_Button(lv_event_t * e);
lv_obj_t * ui_Camera_Button;
void ui_event_Feed_Button(lv_event_t * e);
lv_obj_t * ui_Feed_Button;
lv_obj_t * ui_TDS_Icon;
lv_obj_t * ui_pH_Icon;
lv_obj_t * ui_NTH_Icon;
lv_obj_t * ui_Water_Level_Icon;
lv_obj_t * ui_Water_Temperature_Icon;
lv_obj_t * ui_Pump_Icon;
lv_obj_t * ui_Camera_Icon;
void ui_event_Feed_Dropdown(lv_event_t * e);
lv_obj_t * ui_Feed_Dropdown;
lv_obj_t * ui_Feed_Icon;
void ui_event_Wifi_Button(lv_event_t * e);
lv_obj_t * ui_Wifi_Button;

// SCREEN: ui_Camera
void ui_Camera_screen_init(void);
void ui_event_Camera(lv_event_t * e);
lv_obj_t * ui_Camera;
void ui_event_Camera_Back_Button(lv_event_t * e);
lv_obj_t * ui_Camera_Image;
lv_obj_t * ui_Camera_Back_Button;
void ui_event_Refresh_Button(lv_event_t * e);
lv_obj_t * ui_Refresh_Button;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_QR_Code(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Main_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
    }
}
void ui_event_QR_Code_Back_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Main_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
    }
}
void ui_event_Main_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_QR_Code, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Camera, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        get_camera_image(e);
    }
}
void ui_event_Slave_Dropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        device_selecting_triggered(e);
    }
}
void ui_event_Pump_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        pump_status_switched(e);
    }
}
void ui_event_Camera_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Camera, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
    }
    if(event_code == LV_EVENT_CLICKED) {
        get_camera_image(e);
    }
}
void ui_event_Feed_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        feed_triggered(e);
    }
}
void ui_event_Wifi_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_QR_Code, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
    }
}
void ui_event_Feed_Dropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        update_feed_period(e);
    }
}
void ui_event_Camera(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Main_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
    }
}
void ui_event_Camera_Back_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Main_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
    }
}
void ui_event_Refresh_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        get_camera_image(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_QR_Code_screen_init();
    ui_Main_Screen_screen_init();
    ui_Camera_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main_Screen);
}
