// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: panel

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "esp_log.h"
#include "esp_system.h"
#include "esp_wifi.h"

#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(4, 4, 0)
#include "esp_mac.h"
#endif

#include "espnow.h"
#include "espnow_ctrl.h"
#include "espnow_utils.h"

#ifdef __cplusplus
extern "C" {
#endif

void periodic_timer_callback(void* arg);
void device_selecting_triggered(lv_event_t * e);
void pump_status_switched(lv_event_t * e);
void app_espnow_recv_cb(const esp_now_recv_info_t *recv_info, const uint8_t *data, int len);
void feed_triggered(lv_event_t * e);
void memory_monitor();
void get_camera_image(lv_event_t * e);
void update_feed_period(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
